=== tingumr/resume/Resume/resume.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--Generated by Turbo XML 2.4.1.100. Conforms to w3c http://www.w3.org/2001/XMLSchema-->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
	 elementFormDefault = "qualified">
	<xsd:element name = "resume">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "title" minOccurs = "0"/>
				<xsd:element ref = "summary" minOccurs = "0"/>
				<xsd:element ref = "personalInfo"/>
				<xsd:element ref = "education"/>
				<xsd:element ref = "workExperience"/>
				<xsd:element ref = "skills"/>
				<xsd:element ref = "certifications" minOccurs = "0"/>
				<xsd:element ref = "publications" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "title" type = "xsd:string"/>
	<xsd:element name = "personalInfo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "DOB"/>
				<xsd:element ref = "addressCommunication" minOccurs = "0"/>
				<xsd:element ref = "addressPremanent" minOccurs = "0"/>
				<xsd:element ref = "mobilePhone" minOccurs = "0"/>
				<xsd:element ref = "phone" minOccurs = "0"/>
				<xsd:element ref = "email" minOccurs = "0"/>
				<xsd:element ref = "citizenship" maxOccurs = "unbounded"/>
				<xsd:element ref = "passportno" minOccurs = "0"/>
				<xsd:element ref = "gender"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "name" type = "xsd:string"/>
	<xsd:element name = "DOB" type = "xsd:string"/>
	<xsd:element name = "addressCommunication">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:restriction base = "address">
					<xsd:sequence>
						<xsd:element ref = "AddressLine" maxOccurs = "unbounded"/>
						<xsd:element ref = "City"/>
						<xsd:element ref = "State"/>
						<xsd:element ref = "Country"/>
						<xsd:element ref = "zip"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "addressPremanent">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:restriction base = "address">
					<xsd:sequence>
						<xsd:element ref = "AddressLine" maxOccurs = "unbounded"/>
						<xsd:element ref = "City"/>
						<xsd:element ref = "State"/>
						<xsd:element ref = "Country"/>
						<xsd:element ref = "zip"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "mobilePhone" type = "xsd:string"/>
	<xsd:element name = "phone" type = "xsd:string"/>
	<xsd:element name = "email" type = "xsd:string"/>
	<xsd:complexType name = "address">
		<xsd:sequence minOccurs = "0">
			<xsd:element ref = "AddressLine" maxOccurs = "unbounded"/>
			<xsd:element ref = "City"/>
			<xsd:element ref = "State" minOccurs = "0"/>
			<xsd:element ref = "Country"/>
			<xsd:element ref = "zip" minOccurs = "0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name = "AddressLine" type = "xsd:string"/>
	<xsd:element name = "City" type = "xsd:string"/>
	<xsd:element name = "State" type = "xsd:string"/>
	<xsd:element name = "Country" type = "xsd:string"/>
	<xsd:element name = "zip" type = "xsd:string"/>
	<xsd:element name = "summary">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "info" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "info" type = "xsd:string"/>
	<xsd:element name = "education">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "course" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "course">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "startDate"/>
				<xsd:element ref = "endDate"/>
				<xsd:element ref = "grade"/>
				<xsd:element ref = "institution"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "institution">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "addressPremanent"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "startDate" type = "xsd:string"/>
	<xsd:element name = "endDate" type = "xsd:string"/>
	<xsd:element name = "grade" type = "xsd:string"/>
	<xsd:element name = "experience">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "designation"/>
				<xsd:element ref = "company"/>
				<xsd:element ref = "startDate"/>
				<xsd:element ref = "endDate"/>
				<xsd:element ref = "project" minOccurs = "0" maxOccurs = "unbounded"/>
				<xsd:element ref = "extraInfo" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "company">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "addressPremanent"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "designation" type = "xsd:string"/>
	<xsd:element name = "responsibilities" type = "xsd:string"/>
	<xsd:element name = "project">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "description"/>
				<xsd:element ref = "startDate" minOccurs = "0"/>
				<xsd:element ref = "endDate" minOccurs = "0"/>
				<xsd:element ref = "client" minOccurs = "0"/>
				<xsd:element ref = "URL" minOccurs = "0"/>
				<xsd:element ref = "responsibilities" maxOccurs = "unbounded"/>
				<xsd:element ref = "technology" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "description" type = "xsd:string"/>
	<xsd:element name = "skills">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "technologyArea" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "technologyArea">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "technology" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "technology">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "description" minOccurs = "0"/>
				<xsd:element ref = "proficiency"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "proficiency" type = "xsd:string"/>
	<xsd:element name = "conclusion">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "info" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "citizenship" type = "xsd:string"/>
	<xsd:element name = "gender" type = "xsd:string"/>
	<xsd:element name = "passportno" type = "xsd:string"/>
	<xsd:element name = "certification">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "name"/>
				<xsd:element ref = "date"/>
				<xsd:element ref = "description" minOccurs = "0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "date" type = "xsd:string"/>
	<xsd:element name = "certifications">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "certification" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "publications">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "publication" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "publication">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "title"/>
				<xsd:element ref = "description" minOccurs = "0"/>
				<xsd:element ref = "URL" minOccurs = "0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "URL" type = "xsd:string"/>
	<xsd:element name = "extraInfo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "title"/>
				<xsd:element ref = "info" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "workExperience">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref = "experience" minOccurs = "0" maxOccurs = "unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name = "client" type = "xsd:string"/>
</xsd:schema>

=== tingumr/resume/Resume/resume.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<?xml-stylesheet type="text/xsl" href="resume.xsl"?>
<resume xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "resume.xsd">
	<title>Resume</title>
	<summary>
		<info>Over 10 years of professional experience in developing B2B and B2C Commerce web applications and Enterprise Application Integration.</info>
		<info>Consulting experience working with teams to scale and performance tune web applications with annual revenue in the Billions.</info>
		<info>Agile practitioner who has experience in Technical Training and Team leadership.</info>
	</summary>
	<personalInfo>
		<name>Tingu Ravi</name>
		<DOB>05-07-1979</DOB>
		<addressCommunication>
			<AddressLine>14926</AddressLine>
			<AddressLine>69 Ave</AddressLine>
			<AddressLine></AddressLine>
			<City>Surrey</City>
			<State>British Columbia</State>
			<Country>Canada</Country>
			<zip>V3S0Y8</zip>
		</addressCommunication>
		<addressPremanent>
			<AddressLine>14926</AddressLine>
			<AddressLine>69 Ave</AddressLine>
			<AddressLine></AddressLine>
			<City>Surrey</City>
			<State>British Columbia</State>
			<Country>Canada</Country>
			<zip>V3S0Y8</zip>
		</addressPremanent>
		<phone>604 442 0876</phone>
		<email>travi@xray4j.com</email>
		<citizenship>Canadian Permanent Resident,Indian</citizenship>
		<passportno>B0784312</passportno>
		<gender>Male</gender>
	</personalInfo>
	<education>
		<course>
			<name>Machine Learning</name>
			<startDate>2016</startDate>
			<endDate>2016</endDate>
			<grade>97 %</grade>
			<institution>
				<name>Stanford University - Coursea</name>
				<addressPremanent>
					<AddressLine>https://www.coursera.org/account/accomplishments/certificate/X22Z3WV3EWWX</AddressLine>
					<City>Coursea</City>
					<State>Coursea</State>
					<Country>Coursea</Country>
					<zip/>
				</addressPremanent>
			</institution>
		</course>
		<course>
			<name>Masters in Compuer Science</name>
			<startDate>2001</startDate>
			<endDate>2003</endDate>
			<grade>9.1 CGPA</grade>
			<institution>
				<name>Vellore Institute of Technology</name>
				<addressPremanent>
					<AddressLine>VIT</AddressLine>
					<City>Vellore</City>
					<State>Tamil Nadu</State>
					<Country>India</Country>
					<zip/>
				</addressPremanent>
			</institution>
		</course>
		<course>
			<name>Bachelor Of Computer Application </name>
			<startDate>1998</startDate>
			<endDate>2000</endDate>
			<grade>69%</grade>
			<institution>
				<name>Mahathma Gandhi University</name>
				<addressPremanent>
					<AddressLine>Kottayam</AddressLine>
					<City/>
					<State>Kerala</State>
					<Country>India</Country>
					<zip/>
				</addressPremanent>
			</institution>
		</course>
	</education>
	<workExperience>
		<experience>
		  <designation>Architect</designation>
		  <company>
		    <name>www.xray4j.com</name>
		    <addressPremanent>
		      <AddressLine>10180 153st</AddressLine>
		      <City>Surrey</City>
		      <State>British Columbia</State>
		      <Country>Canada</Country>
		      <zip>V3R 0B5</zip>
		    </addressPremanent>
		  </company>
		  <startDate>16 Aug 2017</startDate>
		  <endDate>Currently Working</endDate>
		  <project>
		    <name>www.xray4j.com</name>
		    <description>Xray4j is a startup that has developed a new way for documenting / troubleshooting/ performance tuning enterprise java applications like Oracle ATG Commerce, Hybris, Broadleaf Commerce.</description>
		    <startDate>Aug 2017</startDate>
		    <endDate>Currently Working</endDate>
				<client>Xray4j</client>
		    <URL>https://www.xray4j.com</URL>
		    <responsibilities>Design the over all architecture for xray4j.</responsibilities>
		    <responsibilities>Implement the java agent and  aspects used to collect data from the JVM and save them to a file.</responsibilities>
		    <responsibilities>Help implement the UI using angularjs.</responsibilities>
				<responsibilities>Create AspectJ instrumentation configuration for ATG Commerce, Hybris, Broadleaf Commerce.</responsibilities>
				<responsibilities>Gain enough exptertise with Vaadin8 to instrument web applications using Vaadin with aspects.</responsibilities>
		    <responsibilities>Design algorithms that represent the collected data from the JVM as easily understandable connected graphs.</responsibilities>
		    <responsibilities>Implement code that displays the most expensive paths for the control flow within a JVM.</responsibilities>
		    <technology>
		      <name>JHipster</name>
		      <proficiency/>
		    </technology>
		    <technology>
		      <name>AngularJs</name>
		      <proficiency/>
		    </technology>
		    <technology>
		      <name>AspectJ</name>
		      <proficiency/>
		    </technology>
		    <technology>
		      <name>AWS EC2</name>
		      <proficiency/>
		    </technology>
				<technology>
					<name>Vaadin8</name>
					<proficiency/>
				</technology>
		    <technology>
		      <name>AWS S3</name>
		      <proficiency/>
		    </technology>
		  </project>
		</experience>
		<experience>
		  <designation>Senior Technology Consultant</designation>
		  <company>
		    <name>SAP Canada</name>
		    <addressPremanent>
		      <AddressLine>910 Mainland St</AddressLine>
		      <City>Vancouver</City>
		      <State>British Columbia</State>
		      <Country>Canada</Country>
		      <zip>V6B 1A9</zip>
		    </addressPremanent>
		  </company>
		  <startDate>12 Jan 2017</startDate>
		  <endDate>15 Aug 2017</endDate>
		  <project>
		    <name>Levi Strauss &amp; Co</name>
		    <description>Played the role of senior developer in the project that was implemented end to end by SAP Hybris.</description>
		    <startDate>March 2017</startDate>
		    <endDate>Aug 2017</endDate>
				<client>Levi</client>
		    <URL>https://www.levi.com/CA/en_CA/</URL>
				<responsibilities>Developed tool to help team debug issues by browsing through beans in the spring context.</responsibilities>
				<responsibilities>Work on integration with Responsys for sending emails.</responsibilities>
		    <responsibilities>Work on the promotion module.</responsibilities>
		    <technology>
		      <name>SAP Hybris</name>
		      <proficiency/>
		    </technology>
		    <technology>
		      <name>Git</name>
		      <proficiency/>
		    </technology>
		  </project>
		</experience>
		<experience>
			<designation>Software Architect</designation>
			<company>
				<name>Rigabyte Inc</name>
				<addressPremanent>
					<AddressLine>10180 153st</AddressLine>
					<City>Surrey</City>
					<State>British Columbia</State>
					<Country>Canada</Country>
					<zip>V3R 0B5</zip>
				</addressPremanent>
			</company>
			<startDate>07 2014</startDate>
			<endDate>11 2016</endDate>
			<project>
				<name>Rigabyte</name>
				<description>Help design and architect a cloud based log management service from the ground up.</description>
				<startDate>Jul 2014</startDate>
				<endDate>Oct 2016</endDate>
				<client>Rigabyte Inc</client>
				<URL>http://www.rigabyte.com</URL>
				<responsibilities>Design the architecture for a high volume log management service.</responsibilities>
				<responsibilities>Set up the production environment on Amazon EC2</responsibilities>
				<responsibilities>Customize Apache Lucene to support high volume of log data processing.</responsibilities>
				<responsibilities>Design and implement agents that collect and deliver data to a cloud service.</responsibilities>
				<responsibilities>Design framework for automated UI tests, integration tests and performance tests.</responsibilities>
				<responsibilities>Implement RESTful webservices required by the application.</responsibilities>
				<responsibilities>Architect the noSQL persistance layer used by the application.</responsibilities>
				<technology>
					<name>Apache Lucene</name>
					<proficiency/>
				</technology>
				<technology>
					<name>Amazon AWS</name>
					<proficiency/>
				</technology>
				<technology>
					<name>Memcached</name>
					<proficiency/>
				</technology>
				<technology>
					<name>JQuery</name>
					<proficiency/>
				</technology>
				<technology>
					<name>Selenium</name>
					<proficiency/>
				</technology>
			</project>
		</experience>
	<experience>
			<designation>Senior Principal Consultant</designation>
			<company>
				<name>Oracle Canada</name>
				<addressPremanent>
					<AddressLine>505 Burrard Street</AddressLine>
					<City>Vancouver</City>
					<State>British Columbia</State>
					<Country>Canada</Country>
					<zip>V7X 1M5</zip>
				</addressPremanent>
			</company>
			<startDate>12 2011</startDate>
			<endDate>07 2014</endDate>
			<project>
				<name>Exito</name>
				<description>Help Exito fix problems with their production architecture for exito.com and ensure exito is able scale to  their fast growing internet traffic.</description>
				<startDate>Jan 2011</startDate>
				<endDate>Jul 2014</endDate>
				<client>Almacenes Ã‰xito S.A</client>
				<URL>http://exito.com</URL>
				<responsibilities>Help migration exito.com from ATG 9.4 to ATG 10.2 and Endeca.</responsibilities>
				<responsibilities>Setup new production / QA environment for the migrated application.</responsibilities>
				<responsibilities>Helped stabilize exito.com after a period of poor stability during the 2011 holiday season(Oct -Dec).</responsibilities>
				<responsibilities>Make architectural changes to exito.com to help with long term scalability. </responsibilities>
				<responsibilities>Help guide a team of 3 developers to implement a number of important change requests for exito.com</responsibilities>
				<responsibilities>Assist Exito do develop inhouse development capability and infrastructure without depending on their existing SI.</responsibilities>
